### ISSUE TITLE
[assignee_no_login] TypeError: UserActivity.get_string_status() missing 1 required positional argument: 'user_creation_time'

### ISSUE THREAD

**Issue by benjaminmah** [mozilla/bugbot#2515]
```
Traceback (most recent call last):
  File "/Users/bmah/bugbot/bugbot/bzcleaner.py", line 856, in run
    self.send_email(date=date)
  File "/Users/bmah/bugbot/bugbot/bzcleaner.py", line 772, in send_email
    data = self.get_email_data(date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bmah/bugbot/bugbot/bzcleaner.py", line 690, in get_email_data
    bugs = self.get_bugs(date=date)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bmah/bugbot/bugbot/rules/assignee_no_login.py", line 63, in get_bugs
    bugs = self.handle_inactive_assignees(bugs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bmah/bugbot/bugbot/rules/assignee_no_login.py", line 87, in handle_inactive_assignees
    bug["assignee_status"] = user_activity.get_string_status(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UserActivity.get_string_status() missing 1 required positional argument: 'user_creation_time'
```

**Comment by suhaibmujahid** [comment]
Regressed by https://github.com/mozilla/bugbot/pull/2457

**Comment by suhaibmujahid** [comment]
I would suggest drop `user_creation_time` as a paramenter in `get_string_status()`. For new users, we could have a new status instead (e.g., `INACTIVE_NEW`).
