### ISSUE TITLE
[needinfo_regression_author] AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#2054]
```
2023-05-11 03:41:50,915 - ERROR - Rule needinfo_regression_author
Traceback (most recent call last):
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 839, in run
    self.send_email(date=date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 762, in send_email
    data = self.get_email_data(date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 682, in get_email_data
    bugs = self.autofix(bugs)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 582, in autofix
    mrg = utils.merge_bz_changes(change, ni_changes.get(bugid, {}))
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by suhaibmujahid** [comment]
Regressed by #2052
